#cloud-config

package_update: true
package_upgrade: true

packages:
  - yum-utils
  - git

runcmd:
  - sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  - sudo yum -y install docker-ce docker-ce-cli containerd.io docker-compose-plugin
  - sudo systemctl start docker
  - sudo systemctl enable docker



